<?php

	//--------------------------------------------------------------------------
	// check if Admin Panel was already installed
	if(!file_exists("inc/config.inc.php")){
		header("location: install.php");
		exit;
	}
    
	session_start();
   error_reporting(E_ERROR); 
    require_once("inc/config.inc.php");
    require_once("inc/settings.inc.php");
    
    $log = (isset($_REQUEST['log'])) ? "out" : "";
    $msg = (isset($_REQUEST['msg'])) ? $_REQUEST['msg'] : "";
    
    $adm_logged = (isset($_SESSION['adm_logged'])) ? $_SESSION['adm_logged'] : false;
    

    if($adm_logged == true){
		$left_menu_page = "left_menu.php";
		$content_page = "home.php";
    }else{	
		$left_menu_page = "left_menu_empty.php";
		$content_page = "login.php";
    }

  
?>


<html>
<head>
    <title><?php echo $SETTINGS['site_name']; ?> :: </title>

    <!-- Meta tags -->    
    <meta http-equiv='Content-Type' content="text/html; charset=UTF-8">

    <!-- CSS style files -->
    <link href="css/style_<?php echo $SETTINGS['css_style']; ?>.css" type="text/css" rel="stylesheet">

    <!-- JavaScript files -->
    <script type="text/JavaScript" src="js/functions.js"></script>         
</head>

<frameset rows="90px,*" FRAMEBORDER="no" FRAMESPACING="0" BORDER="0">
     <frame src="header.php" name="header" scrolling="no">
     <frameset cols="170px,*"  FRAMEBORDER="no" FRAMESPACING="0" BORDER="0">
          <frame src="<?php echo $left_menu_page; ?>" name="left_menu" scrolling="no">
          <frame src="<?php echo $content_page; ?>" name="frameMain">
     </frameset>
</frameset>
<!-- This script was generated by PHPAP (ApPHP AdminPanel) v1.0.5 | http://www.apphp.com/php-adminpanel/index.php -->
</html>
