// default package
// Generated Mar 8, 2014 1:06:30 PM by Hibernate Tools 3.4.0.CR1
package model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedProperty;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Member generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "member", catalog = "clickcart")
public class Member implements java.io.Serializable {

	private Integer id;
	private String mname;
	private String company;
	private String address;
	private Integer bakiye;
	private String status;
	private String email;
	private String yetkili;
	private String username;
	private String password;
	private String membercol;
	private Set<Cart> carts = new HashSet<Cart>(0);
	private Set<Move> moves = new HashSet<Move>(0);
	

	public Member() {
	}

	public Member(String mname, String company, String address, Integer bakiye,
			String status, String email, String yetkili, String username,
			String password, String membercol, Set<Cart> carts, Set<Move> moves) {
		this.mname = mname;
		this.company = company;
		this.address = address;
		this.bakiye = bakiye;
		this.status = status;
		this.email = email;
		this.yetkili = yetkili;
		this.username = username;
		this.password = password;
		this.membercol = membercol;
		this.carts = carts;
		this.moves = moves;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "mname")
	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	@Column(name = "company")
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "bakiye")
	public Integer getBakiye() {
		return this.bakiye;
	}

	public void setBakiye(Integer bakiye) {
		this.bakiye = bakiye;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "yetkili", length = 100)
	public String getYetkili() {
		return this.yetkili;
	}

	public void setYetkili(String yetkili) {
		this.yetkili = yetkili;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "membercol", length = 45)
	public String getMembercol() {
		return this.membercol;
	}

	public void setMembercol(String membercol) {
		this.membercol = membercol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Cart> getCarts() {
		return this.carts;
	}

	public void setCarts(Set<Cart> carts) {
		this.carts = carts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public Set<Move> getMoves() {
		return this.moves;
	}

	public void setMoves(Set<Move> moves) {
		this.moves = moves;
	}

}
