// default package
// Generated Mar 8, 2014 1:06:30 PM by Hibernate Tools 3.4.0.CR1
package model;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Move generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "move", catalog = "clickcart")
public class Move implements java.io.Serializable {

	private Integer id;
	private Member member;
	private Cart cart;
	private Date tarih;
	private String type;
	private String desc;
	private Member user;
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "member")
	public Member getUser() {
		return user;
	}

	public void setUser(Member user) {
		this.user = user;
	}

	@Column(name = "desc", length = 255)
	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public Move() {
	}

	public Move(Member member, Cart cart, Date tarih, String type) {
		this.member = member;
		this.cart = cart;
		this.tarih = tarih;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "toId")
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fromId")
	public Cart getCart() {
		return this.cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tarih", length = 0)
	public Date getTarih() {
		return this.tarih;
	}

	public void setTarih(Date tarih) {
		this.tarih = tarih;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
